#!/bin/bash
set -e -v -o pipefail

cd "$(dirname "$0")"

# zim
# Copy https://github.com/zimfw/zimfw/releases/latest/download/zimfw.zsh to ~/.zim/zimfw.zsh
ln -s ~/.home/zim/zimrc ~/.zimrc
ln -s ~/.home/zim/zlogin ~/.zlogin
ln -s ~/.home/zim/zshenv ~/.zshenv
ln -s ~/.home/zim/zshrc ~/.zshrc

# directories
# stop if exists? rm -rf .vim;
ln -s ~/.home/vim/vimrc ~/.vimrc
mkdir -p ~/.vim/{autoload,swap,undo}
ln -s ~/.home/vim/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim

# git
ln -s ~/.home/git/gitconfig .gitconfig
ln -s ~/.home/git/gitignore_global .gitignore_global

# xmonad
ln -s ~/.home/xmonad/xmobarrc ~/.xmobarrc
mkdir -p .xmonad
ln -s ~/.home/xmonad/xmonad.hs ~/.xmonad/xmonad.hs

# urxvt
mkdir -p ~/.urxvt/ext
ln -s ~/.home/urxvt/focus ~/.urxvt/perl/focus
ln -s ~/.home/Xdefaults .Xdefaults
ln -s ~/.home/Xresources .Xresources

# X
touch .startxmonad
ln -sf ~/.home/xinitrc .xinitrc
ln -sf ~/.home/.Xmodmap .Xmodmap
sudo cp ~/.home/xrandr/60-detect-dpi.sh /etc/X11/xinit/xinitrc.d/60-detect-dpi.sh

# intel
sudo cp ~/.home/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf
