#!/bin/bash
set -e -v -o pipefail

cd "$(dirname "$0")"

# prezto
git submodule update --init --recursive
cd prezto
git checkout custom
ln -sf ~/.home/prezto ~/.zprezto
setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done

cd ~

# directories
rm -rf .vim; ln -sf ~/.home/vim .vim

# git
ln -s ~/.home/git/gitconfig .gitconfig
ln -s ~/.home/git/gitignore_global .gitignore_global

# xmonad
ln -s ~/.home/xmonad/xmobarrc .xmobarrc
mkdir -p .xmonad/hooks
ln -s ~/.home/xmonad/xmonad.hs .xmonad/xmonad.hs
ln -s ~/.home/xmonad/lock.sh .xmonad/hooks/lock

# urxvt
mkdir -p ~/.urxvt/ext
ln -s ~/.home/urxvt/focus ~/.urxvt/perl/focus
ln -s ~/.home/Xdefaults .Xdefaults
ln -s ~/.home/Xresources .Xresources

# X
touch .startxmonad
ln -sf ~/.home/xinitrc .xinitrc
ln -sf ~/.home/.Xmodmap .Xmodmap
sudo cp ~/.home/xrandr/60-detect-dpi.sh /etc/X11/xinit/xinitrc.d/60-detect-dpi.sh

# intel
sudo cp ~/.home/20-intel.conf /etc/X11/xorg.conf.d/20-intel.conf
